#!/bin/bash

MSG=\
"It is highly recommended to use Linaro toolchain with GCC 4.7 to build this"\
"\nkernel. It is known issue that GCC newer than 4.7 produces broken image "\
"that\nwill not even boot. Alternatively, you can cross fingers and re-run "\
"this script with --download option.\n\n"\
"Useful links:\nhttps://gcc.gnu.org/faq.html#multiple\nhttps://wiki.linaro.or"\
"g/Cbuildv2\n"

CMD=arm-linux-gnueabihf-gcc

echo -n "Checking GCC version... "
if $CMD --version 2>/dev/null | grep "4.[3-7]." \
					> /dev/null 2>/dev/null; then
	echo "OK"
	exit 0
else
	if type $CMD >/dev/null 2>/dev/null; then
		echo -e "Unsupported\n"
		echo -en $MSG
		exit 1
	fi
	echo -e "Not installed\n"
	echo -en $MSG
	exit 2
fi
